#!/usr/bin/env bash
# baah script to transfer file from client to server
if [ "$#" -lt 3 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit 
elif [ "$#" -lt 4 ]; then
        scp -o StricHostKeyChecking=no "$1" "$3@$2":~/
else
        scp -i "$4" -o StricHostKeyChecking=no "$1" "$3@$2":~/
fi;
