#!/usr/bin/env bash
# install ngix server
apt-get update
apt-get -y install nginx


echo "Hello World!" > /var/www/html/index.html

state=$(pgrep nginx)
if [ -n "$state" ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
