#!/usr/bin/env bash
# install ngix server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo echo "Hello World" > /usr/share/nginx/html/index.html
sudo service nginx restart
