#!/usr/bin/env bash
## Create a script to install and configure HAProxy on lb-01 server
ckage list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    balance roundrobin
    server web-01 54.175.18.167:80 check
    server web-02 35.174.207.14:80 check
EOF

# Enable HAProxy service to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
