#!/usr/bin/env bash 
# display file
#display infinity and beyond and i hate the kill command and y love me
terminator()
{
	rm /var/run/myscript.pid
	exit
}
echo $$ >> /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'Y U no love me?!'" SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
