#!/usr/bin/env bash
# This script is displaying "Best School"
#and write bad luck after 3 and good luck after 8
count=0
while [ $count -lt 10 ]
do
if [ $count -eq 3 ]
then
echo "bad luck"
elif [ $count -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
(( count++ ))
done
