#!/usr/bin/env bash
#print bad luck after 4 from china after 9 from japan after 17 from italy
count=1
while [ $count -le 20 ]
do
echo "$count"
case $count in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( count++ ))
done
