#!/usr/bin/env bash
# Client configuration file
Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHost yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
